-- Autogenerated with DRAKON Editor 1.32
local table = table
local string = string
local pairs = pairs
local ipairs = ipairs
local type = type
local box = box
local tostring = tostring
local tonumber = tonumber
local print = print
local math = math
local os = os
local error = error
local global_cfg = global_cfg
local globs = globs
local pcall = pcall

local clock = require("clock")
local log = require("log")
local digest = require("digest")
local fiber = require("fiber")
local utils = require("utils")
local fun = require("fun")
local json = require("json")

local utf8 = require("lua-utf8")

local folders = box.space.folders
local items = box.space.items
local spaces = box.space.spaces
local usettings = box.space.usettings
local recent = box.space.recent
local rights = box.space.rights
local trash = box.space.trash
local folder_tree = box.space.folder_tree

local users = box.space.users
local sessions = box.space.sessions
local creds = box.space.creds
local usecrets = box.space.usecrets

local payments = box.space.payments
local agreements = box.space.agreements
local scheduled = box.space.scheduled
local transactions = box.space.transactions
local licenses = box.space.licenses
local coupons = box.space.coupons

local search_yield = 0.02
local current_version = 20180619

local module = {}
module.transactions = {}

setfenv(1, {}) 

function agreement_delete(id)
    -- item 602
    agreements:delete(
        {id}
    )
end

function agreement_get(id)
    local row
    -- item 590
    row = agreements:get(id)
    -- item 593
    if row then
        -- item 592
        return row[3], row[2]
    else
        -- item 596
        return nil
    end
end

function agreement_get_by_order_ref(order_ref)
    local found, index
    -- item 609
    index = agreements.index.by_order
    -- item 608
    found = index:select(
        order_ref,
        {iterator = "EQ"}
    )
    -- item 610
    return found
end

function agreement_insert(id, order_ref, data)
    -- item 616
    agreements:insert {
    	id,
    	order_ref,
    	data
    }
end

function agreement_update(agreement_id, order_ref, data)
    -- item 622
    agreements:replace {
    	agreement_id,
    	order_ref,
    	data
    }
end

function agreement_update_data(agreement_id, agreement)
    -- item 805
    agreements:update(
    	agreement_id,
    	{{"=", 3, agreement }}
    )
end

function agreement_update_order(agreement_id, order_ref)
    -- item 629
    utils.update2(
    	agreements,
    	agreement_id,
    	order_ref
    )
end

function begin()
    local id
    -- item 828
    id = get_fiber_id()
    -- item 842
    if module.transactions[id] then
        -- item 845
        error("Already in transaction")
    else
        -- item 829
        module.transactions[id] = true
        -- item 809
        box.begin()
    end
end

function clean_up()
    local id
    -- item 835
    id = get_fiber_id()
    -- item 837
    if module.transactions[id] then
        -- item 834
        box.rollback()
        -- item 836
        module.transactions[id] = nil
    end
end

function commit()
    local id
    -- item 830
    id = get_fiber_id()
    -- item 846
    if module.transactions[id] then
        -- item 813
        box.commit()
        -- item 831
        module.transactions[id] = nil
    else
        -- item 849
        error("Not in transaction")
    end
end

function coupon_get(code)
    local data, row
    -- item 756
    row = coupons:get(code)
    -- item 757
    if row then
        -- item 762
        data = row[2]
        -- item 761
        return data
    else
        -- item 760
        return nil
    end
end

function coupon_insert(code, data)
    -- item 749
    coupons:insert {
    	code,
    	data
    }
end

function coupon_update(code, data)
    -- item 770
    coupons:replace {
    	code,
    	data
    }
end

function cred_delete(user_id)
    -- item 523
    creds:delete{user_id}
end

function cred_get(user_id)
    local row
    -- item 505
    row = creds:get(user_id)
    -- item 506
    if row then
        -- item 510
        return row[2]
    else
        -- item 509
        return nil
    end
end

function cred_upsert(user_id, cred)
    -- item 516
    creds:replace{user_id, cred}
end

function folder_delete(space_id, folder_id)
    -- item 284
    folders:delete(
        {space_id, folder_id}
    )
end

function folder_get(space_id, folder_id)
    local folder
    -- item 267
    folder = folders:get(
        {space_id, folder_id}
    )
    -- item 270
    if folder then
        -- item 269
        local fdata = folder[3]
        -- item 268
        return fdata
    else
        -- item 273
        return nil
    end
end

function folder_get_all()
    -- item 774
    return folders:select()
end

function folder_get_by_space(space_id)
    -- item 291
    return folders:select(
        {space_id}
    )
end

function folder_insert(space_id, folder_id, fdata)
    -- item 279
    folders:insert(
        {space_id, folder_id, fdata}
    )
end

function folder_tree_delete(space_id, folder_id)
    -- item 963
    folder_tree:delete {
    	space_id,
    	folder_id
    }
end

function folder_tree_get(space_id, folder_id)
    local row
    -- item 981
    row = folder_tree:get {
    	space_id,
    	folder_id
    }
    -- item 977
    if row then
        -- item 976
        return row[3]
    else
        -- item 980
        return nil
    end
end

function folder_tree_get_by_parent(space_id, parent_id)
    -- item 982
    return folder_tree.index.by_parent:select {
    	space_id,
    	parent_id
    }
end

function folder_tree_upsert(space_id, folder_id, parent_id)
    -- item 957
    folder_tree:replace {
    	space_id,
    	folder_id,
    	parent_id,
    	{}
    }
end

function folder_update(space_id, folder_id, fdata)
    -- item 296
    utils.update3(
        folders,
        space_id,
        folder_id,
        fdata
    )
end

function get_fiber_id()
    -- item 827
    return fiber.self():id()
end

function invoke_no_throw(action, description)
    -- item 859
    local ok, result = pcall(action)
    -- item 860
    if ok then
        -- item 864
        return result
    else
        -- item 863
        log.error(
          "error: "
          .. tostring(description)
          .. tostring(result)
        )
        -- item 866
        clean_up()
        -- item 865
        return nil
    end
end

function item_count()
    -- item 779
    return items:count()
end

function item_delete(space_id, folder_id, item_id)
    -- item 325
    items:delete(
        {space_id, folder_id, item_id}
    )
end

function item_get(space_id, folder_id, item_id)
    local item
    -- item 303
    item = items:get{
    	space_id,
    	folder_id,
    	item_id
    }
    -- item 304
    if item then
        -- item 308
        return item[4]
    else
        -- item 307
        return nil
    end
end

function item_get_by_folder(space_id, folder_id)
    -- item 331
    return items:select(
        {space_id, folder_id}
    )
end

function item_insert(space_id, folder_id, item_id, idata)
    -- item 319
    items:insert(
        {space_id, folder_id, item_id, idata}
    )
end

function item_update(space_id, folder_id, item_id, idata)
    -- item 314
    utils.update4(
    	items,
    	space_id,
    	folder_id,
    	item_id,
    	idata
    )
end

function license_delete(id)
    -- item 702
    licenses:delete(id)
end

function license_get(id)
    local data, row
    -- item 708
    row = licenses:get(id)
    -- item 712
    if row then
        -- item 709
        data = row[2]
        -- item 710
        return data
    else
        -- item 711
        return nil
    end
end

function license_insert(data)
    local id, row
    -- item 695
    row = licenses:auto_increment {
    	data
    }
    -- item 696
    id = row[1]
    -- item 875
    return id
end

function license_update(id, data)
    -- item 720
    licenses:replace {
    	id,
    	data
    }
end

function payment_delete(payment_id)
    -- item 578
    payments:delete(
        {payment_id}
    )
end

function payment_get_by_user(user_id)
    -- item 572
    return payments.index.by_user:select(
        user_id
    )
end

function payment_insert(user_id, payment)
    -- item 584
    payments:auto_increment {user_id, payment}
end

function recent_delete(space_id, folder_id, user_id)
    -- item 389
    recent:delete {
    	space_id,
    	folder_id,
    	user_id
    }
end

function recent_get_by_folder(space_id, folder_id)
    -- item 377
    return recent:select(
        {space_id, folder_id}
    )
end

function recent_get_by_user(user_id)
    -- item 383
    return recent.index.by_user:select{user_id}
end

function recent_upsert(space_id, folder_id, user_id, data)
    -- item 371
    utils.write4(
    	recent,
    	space_id,
    	folder_id,
    	user_id,
    	data
    )
end

function rights_delete(space_id, user_id, access)
    -- item 918
    rights:delete(
        {space_id, user_id, access}
    )
end

function rights_delete_by_space(space_id)
    local access, rows, user_id
    -- item 920
    rows = rights_get_by_space(space_id)
    for _, row in ipairs(rows) do
        -- item 923
        user_id = row[2]
        access = row[3]
        -- item 924
        rights:delete(
            {space_id, user_id, access}
        )
    end
end

function rights_delete_by_user(user_id)
    local access, rows, space_id
    -- item 926
    rows = rights_get_by_user(user_id)
    for _, row in ipairs(rows) do
        -- item 929
        space_id = row[1]
        access = row[3]
        -- item 930
        rights:delete(
            {space_id, user_id, access}
        )
    end
end

function rights_get_by_space(space_id)
    -- item 893
    return rights:select {space_id}
end

function rights_get_by_space_user(space_id, user_id)
    -- item 931
    return rights:select {space_id, user_id}
end

function rights_get_by_user(user_id)
    -- item 925
    return rights.index.by_user:select(user_id)
end

function rights_insert(space_id, user_id, access, data)
    -- item 919
    rights:insert(
        {space_id, user_id, access, data}
    )
end

function rollback()
    local id
    -- item 832
    id = get_fiber_id()
    -- item 850
    if module.transactions[id] then
        -- item 817
        box.rollback()
        -- item 833
        module.transactions[id] = nil
    else
        -- item 853
        error("Not in transaction")
    end
end

function run_in_fiber(action, description)
    -- item 873
    local safe_action = function()
    	invoke_no_throw(action, description)
    end
    -- item 872
    fiber.create(safe_action)
end

function scheduled_delete(agreement_id)
    -- item 635
    scheduled:delete(agreement_id)
end

function scheduled_get(agreement_id)
    -- item 641
    local srow = scheduled:get(agreement_id)
    -- item 642
    if srow then
        -- item 646
        return srow[2]
    else
        -- item 645
        return nil
    end
end

function scheduled_get_all()
    -- item 799
    return scheduled:select()
end

function scheduled_upsert(agreement_id, data)
    -- item 652
    scheduled:replace {
    	agreement_id,
    	data
    }
end

function session_count()
    -- item 787
    return sessions:count()
end

function session_delete(session_id)
    -- item 487
    sessions:delete(
        {session_id}
    )
end

function session_get(session_id)
    -- item 481
    return sessions:get(
        {session_id}
    )
end

function session_get_by_user(user_id)
    -- item 475
    return sessions.index.by_user:select(user_id)
end

function session_insert(session_id, user_id, sdata)
    -- item 493
    sessions:insert(
        {session_id, user_id, sdata}
    )
end

function session_update(session_id, user_id, sdata)
    -- item 499
    sessions:replace{session_id, user_id, sdata}
end

function space_count()
    -- item 783
    return spaces:count()
end

function space_delete(space_id)
    -- item 355
    spaces:delete(
        {space_id}
    )
end

function space_get(space_id)
    local space
    -- item 338
    space = spaces:get(
        {space_id}
    )
    -- item 340
    if space then
        -- item 339
        return space[2]
    else
        -- item 343
        return nil
    end
end

function space_get_all()
    -- item 359
    return spaces:select()
end

function space_insert(space_id, sdata)
    -- item 349
    spaces:insert{ space_id, sdata }
end

function space_update(space_id, sdata)
    -- item 364
    utils.update2(
        spaces,
        space_id,
        sdata
    )
end

function stats_get(req, session, headers)
    local diagrams, users
    -- item 559
    local dia_count = 0
    for key, tuple in folders:pairs() do
        -- item 562
        local fdata = tuple[3]
        -- item 563
        if fdata.type == "folder" then
            
        else
            -- item 566
            dia_count = dia_count + 1
        end
    end
    -- item 556
    local rdata = {
    	users = users:count(),
    	diagrams = dia_count
    }
    -- item 554
    return rdata
end

function transaction_delete(id)
    -- item 689
    transactions:delete(id)
end

function transaction_get(id)
    local data, row, user_id
    -- item 658
    row = transactions:get(id)
    -- item 659
    if row then
        -- item 664
        id = row[1]
        user_id = row[2]
        data = row[3]
        data.user_id = user_id
        data.id = id
        -- item 665
        return data
    else
        -- item 662
        return nil
    end
end

function transaction_get_by_user(user_id)
    -- item 677
    return transactions.index.by_user:select(user_id)
end

function transaction_insert(id, user_id, tdata)
    -- item 671
    transactions:insert {
    	id,
    	user_id,
    	tdata
    }
end

function transaction_update(id, user_id, tdata)
    -- item 683
    transactions:replace {
    	id,
    	user_id,
    	tdata
    }
end

function trash_delete(space_id, folder_id)
    -- item 949
    trash:delete(
        {space_id, folder_id}
    )
end

function trash_get_all()
    -- item 988
    return trash:select()
end

function trash_get_by_space(space_id)
    -- item 951
    return trash:select(
        {space_id}
    )
end

function trash_insert(space_id, folder_id)
    -- item 950
    trash:insert(
        {space_id, folder_id, {}}
    )
end

function usecret_delete(user_id)
    -- item 546
    usecrets:delete{user_id}
end

function usecret_get(user_id)
    local row
    -- item 529
    row = usecrets:get(user_id)
    -- item 530
    if row then
        -- item 534
        return row[2]
    else
        -- item 533
        return nil
    end
end

function usecret_upsert(user_id, cred)
    -- item 540
    usecrets:replace{user_id, cred}
end

function user_count()
    -- item 793
    return users:count()
end

function user_delete(user_id)
    -- item 441
    users:delete { user_id }
end

function user_get(user_id)
    -- item 429
    return users:get(
        {user_id}
    )
end

function user_get_all()
    -- item 457
    return users:select()
end

function user_get_by_email(email)
    -- item 447
    return users.index.by_email:get(email)
end

function user_get_email(user_id)
    local user
    -- item 418
    user = users:get(
        {user_id}
    )
    -- item 420
    if user then
        -- item 419
        return user[2]
    else
        -- item 423
        return nil
    end
end

function user_insert(id, email, data)
    -- item 435
    users:insert {id, email, data}
end

function user_update(id, email, data)
    -- item 453
    users:replace {id, email, data}
end

function usettings_delete(user_id)
    -- item 412
    usettings:delete(user_id)
end

function usettings_get(user_id)
    local row
    -- item 401
    row = usettings:get(user_id)
    -- item 402
    if row then
        -- item 406
        return row[2]
    else
        -- item 405
        return nil
    end
end

function usettings_upsert(user_id, data)
    -- item 395
    utils.write2(
    	usettings,
    	user_id,
    	data
    )
end


return {
folder_get = folder_get,
folder_insert = folder_insert,
folder_delete = folder_delete,
folder_get_by_space = folder_get_by_space,
folder_update = folder_update,
folder_get_all = folder_get_all,

item_get = item_get,
item_update = item_update,
item_insert = item_insert,
item_delete = item_delete,
item_get_by_folder = item_get_by_folder,

space_get = space_get,
space_insert = space_insert,
space_delete = space_delete,
space_get_all = space_get_all,
space_update = space_update,

usettings_upsert = usettings_upsert,
usettings_get = usettings_get,
usettings_delete = usettings_delete,

recent_upsert = recent_upsert,
recent_get_by_folder = recent_get_by_folder,
recent_get_by_user = recent_get_by_user,
recent_delete = recent_delete,

begin = begin,
commit = commit,
rollback = rollback,
clean_up = clean_up,

user_get_email = user_get_email,
user_get = user_get,
user_insert = user_insert,
user_delete = user_delete,
user_get_by_email = user_get_by_email,
user_update = user_update,
user_get_all = user_get_all,

session_get_by_user = session_get_by_user,
session_get = session_get,
session_delete = session_delete,
session_insert = session_insert,
session_update = session_update,

usecret_get = usecret_get,
usecret_upsert = usecret_upsert,
usecret_delete = usecret_delete,

cred_get = cred_get,
cred_upsert = cred_upsert,
cred_delete = cred_delete,

stats_get = stats_get,

payment_get_by_user = payment_get_by_user,
payment_delete = payment_delete,
payment_insert = payment_insert,

agreement_get = agreement_get,
agreement_delete = agreement_delete,
agreement_get_by_order_ref = agreement_get_by_order_ref,
agreement_insert = agreement_insert,
agreement_update = agreement_update,
agreement_update_order = agreement_update_order,
agreement_update_data = agreement_update_data,

transaction_get = transaction_get,
transaction_insert = transaction_insert,
transaction_get_by_user = transaction_get_by_user,
transaction_update = transaction_update,
transaction_delete = transaction_delete,

license_insert = license_insert,
license_delete = license_delete,
license_get = license_get,
license_update = license_update,

coupon_insert = coupon_insert,
coupon_get = coupon_get,
coupon_update = coupon_update,

scheduled_delete = scheduled_delete,
scheduled_get = scheduled_get,
scheduled_upsert = scheduled_upsert,
scheduled_get_all = scheduled_get_all,

item_count = item_count,
space_count = space_count,
user_count = user_count,
session_count = session_count,

rights_insert = rights_insert,
rights_delete = rights_delete,
rights_get_by_space = rights_get_by_space,
rights_get_by_user = rights_get_by_user,
rights_get_by_space_user = rights_get_by_space_user,
rights_delete_by_space = rights_delete_by_space,
rights_delete_by_user = rights_delete_by_user,

trash_get_by_space = trash_get_by_space,
trash_insert = trash_insert,
trash_delete = trash_delete,
trash_get_all = trash_get_all,

folder_tree_upsert = folder_tree_upsert,
folder_tree_delete = folder_tree_delete,
folder_tree_get_by_parent = folder_tree_get_by_parent,
folder_tree_get = folder_tree_get,

invoke_no_throw = invoke_no_throw,
run_in_fiber = run_in_fiber
}
