#!/bin/bash

rm -rf old
rm -rf dewt

unzip $1

mkdir old
cp -r /dewt/app old
cp -r /dewt/static old
cp -r /dewt/emails old
cp -r /dewt/content old
cp -r /dewt/read old

cp -r dewt/app /dewt
cp -r dewt/static /dewt
cp -r dewt/emails /dewt
cp -r dewt/content /dewt
cp -r dewt/read /dewt
