#!/bin/bash

# Configures iptables for a public web server based on Tarantool and nginx:
# 1. Ports 8090 (drakon editor) and 3301 (tarantool) are accessible only from localhost
# 2. 80 -> 8080
# 3. 443 -> 8083

# Remove all rules
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X

# Block 8090,3301

iptables -A INPUT -i lo -p tcp --dport 8090 -j ACCEPT
iptables -A INPUT -i lo -p tcp --dport 3301 -j ACCEPT

iptables -A INPUT -p tcp --dport 8090 -j DROP
iptables -A INPUT -p tcp --dport 3301 -j DROP




# Redirect 80 -> 8080
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A OUTPUT -o lo -p tcp --dport 80 -j REDIRECT --to-port 8080

# Redirect 443 -> 8083
iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 8083
iptables -t nat -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8083
